c_compiler_version:
  - 7                          # [linux64]
cxx_compiler_version:
  - 7                          # [linux64]
c_compiler:                     # [win]
  - vs2019                       # [win]
cxx_compiler:                    # [win]
  - vs2019                       # [win]