c_compiler:                    # [win]
  - vs2019                     # [win]
cxx_compiler:                  # [win]
  - vs2019                     # [win]
cuda_compiler_version:
  - None                       # [os.environ.get("CF_CUDA_ENABLED", "False") == "False"]
