{% set version = "5.5.992" %}
{% set commit = "a92babfe74532bc2612d7f342d8f668e592413f9" %}
{% set kaldi_proc_type = "cuda" if cuda_compiler_version != "None" else "cpu" %}

package:
  name: kaldi
  version: {{ version }}

source:
  fn: {{ version }}-{{ commit }}.tar.gz
  url: https://github.com/kaldi-asr/kaldi/archive/a92babfe74532bc2612d7f342d8f668e592413f9.tar.gz
  sha256: 66f3731e0c23efed870e8956be876436ffe44ea823814c895af779531904715b
  patches:
    - cmake.patch

build:
  number: 8
  skip: true  # [cuda_compiler_version == "10.2"]
  run_exports:
    - {{ pin_subpackage('kaldi', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}

outputs:
  - name: kaldi
    build:
      string: cuda{{ cuda_compiler_version | replace('.', '') }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
      string: cpu_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}                                      # [cuda_compiler_version == "None"]
      script_env:
        - MATHLIB=MKL  # [x86]
        - MATHLIB=OpenBLAS  # [not x86]
    script: build_kaldi.sh  # [not win]
    script: bld_kaldi.bat   # [win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ compiler('fortran') }}  # [not win]
        - {{ compiler('cuda') }}  # [cuda_compiler_version != "None"]
        - cmake
        - ninja
        - m2-patch  # [win]
        - libtool  # [not win]
        - automake  # [not win]
      host:
        - pthreads-win32        # [win]
        - mkl-devel             # [x86]
        - mkl        # [x86]
        - libblas * *mkl       # [x86]
        - libcblas * *mkl       # [x86]
        - liblapack * *mkl       # [x86]
        - libblas * *openblas               # [not x86]
        - libcblas * *openblas             # [not x86]
        - liblapack * *openblas             # [not x86]
        - openblas              # [not x86]
        - blas-devel            # [not x86]
        - zlib
        - icu
      run:
        - mkl         # [x86]
        - libblas * *mkl       # [x86]
        - libcblas * *mkl       # [x86]
        - liblapack * *mkl       # [x86]
        - libblas * *openblas               # [not x86]
        - libcblas * *openblas             # [not x86]
        - liblapack * *openblas            # [not x86]
        - openblas             # [not x86]
        - openfst  # [not win and build_platform == target_platform]

  {% set kaldi_cpu_gpu = "kaldi-cpu" %}   # [cuda_compiler_version == "None"]
  {% set kaldi_cpu_gpu = "kaldi-cuda" %}   # [cuda_compiler_version != "None"]
  - name: {{ kaldi_cpu_gpu }}
    build:
      string: cuda{{ cuda_compiler_version | replace('.', '') }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
      string: cpu_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}                                      # [cuda_compiler_version == "None"]
      detect_binary_files_with_prefix: False
      # weigh down cpu implementation and give cuda preference
      track_features:
        - kaldi-cpu                                      # [cuda_compiler_version == "None"]
    requirements:
      run:
        - {{ pin_subpackage("kaldi", exact=True) }}
    files:
      # Include files like
      #   - libopenblasp-r0.3.5.so
      #   - libopenblas_vortexp-r0.3.5.so
      #   - libopenblas.so.0
      # Avoid files
      #   - libkaldi.lib
      #   - include/kaldi/io-funcs.h
      - lib/libkaldi*{{ SHLIB_EXT }}   # [not win]
      - lib/libkaldi.so.*               # [linux]
      - lib/libkaldi.*.dylib            # [osx]
      - bin/*   # [not win]
      - Library/bin/*           # [win]

  {% set kaldi_cpu_gpu_dev = "kaldi-cpu-dev" %}   # [cuda_compiler_version == "None"]
  {% set kaldi_cpu_gpu_dev = "kaldi-cuda-dev" %}   # [cuda_compiler_version != "None"]
  - name: {{ kaldi_cpu_gpu_dev }}
    build:
      string: cuda{{ cuda_compiler_version | replace('.', '') }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
      string: cpu_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}                                      # [cuda_compiler_version == "None"]
      detect_binary_files_with_prefix: False
      # weigh down cpu implementation and give cuda preference
      track_features:
        - {{ kaldi_cpu_gpu_dev }}
    requirements:
      run:
        - {{ pin_subpackage("kaldi-cpu", exact=True) }}  # [cuda_compiler_version == "None"]
        - {{ pin_subpackage("kaldi-cuda", exact=True) }}  # [cuda_compiler_version != "None"]
    files:
      - include/kaldi/*/*.h  # [not win]
      - Library/include/kaldi/*/*.h  # [win]
      - Library/include/fst/*.h  # [win]
      - Library/lib/libkaldi*.lib  # [win]
    test:
      commands:
        - test -f ${PREFIX}/include/kaldi/base/io-funcs.h  # [not win]
        - if not exist %PREFIX%\\Library\\lib\\fst.lib exit 1  # [win]
        - if not exist %PREFIX%\\Library\\lib\\kaldi-base.lib exit 1  # [win]


about:
  home: http://kaldi-asr.org/
  license: Apache-2.0
  license_file: COPYING
  summary: 'Kaldi is a toolkit for speech recognition written in C++.'
  description: |
    Kaldi is intended for use by speech recognition researchers. It is a framework rather than a library.
  doc_url: http://kaldi-asr.org/doc
  dev_url: http://kaldi-asr.org/forums.html

extra:
  recipe-maintainers:
    - mmcauliffe
    - mcernak
