{% set version = "5.5.992" %}
{% set commit = "a92babfe74532bc2612d7f342d8f668e592413f9" %}
{% set kaldi_proc_type = "cuda" if cuda_compiler_version != "None" else "cpu" %}

package:
  name: kaldi
  version: {{ version }}

source:
  fn: {{ version }}-{{ commit }}.tar.gz
  url: https://github.com/kaldi-asr/kaldi/archive/a92babfe74532bc2612d7f342d8f668e592413f9.tar.gz
  sha256: 66f3731e0c23efed870e8956be876436ffe44ea823814c895af779531904715b
  patches:
    - cmake.patch

build:
  number: 5
  skip: true  # [cuda_compiler_version == "10.2"]

requirements:
  build:
    - {{ compiler('cxx') }}

outputs:
  - name: kaldi
    build:
      string: cuda{{ cuda_compiler_version | replace('.', '') }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
      string: cpu_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}                                      # [cuda_compiler_version == "None"]
      script_env:
        - CPPFLAGS="-std=c++14"  # [win]
        - CXXFLAGS="-std=c++14 -Wno-deprecated-declarations"  # [win]
        - CMAKE_CXX_STANDARD=14  # [win]
        - MATHLIB=MKL  # [x86]
        - MATHLIB=OpenBLAS  # [not x86]
      run_exports:
        # ensure matching proc-type
        - kaldi =*=*_{{ kaldi_proc_type }}
    script: build_kaldi.sh  # [not win]
    script: bld_kaldi.bat   # [win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ compiler('fortran') }}  # [not win]
        - {{ compiler('cuda') }}  # [cuda_compiler_version != "None"]
        - cmake
        - ninja
        - m2-patch  # [win]
        - libtool  # [not win]
        - automake  # [not win]
      host:
        - pthreads-win32        # [win]
        - mkl-devel             # [x86]
        - mkl        # [x86]
        - libblas * *mkl       # [x86]
        - libcblas * *mkl       # [x86]
        - liblapack * *mkl       # [x86]
        - libblas * *openblas               # [not x86]
        - libcblas * *openblas             # [not x86]
        - liblapack * *openblas             # [not x86]
        - openblas              # [not x86]
        - blas-devel            # [not x86]
        - zlib
        - icu
      run:
        - mkl         # [x86]
        - libblas * *mkl       # [x86]
        - libcblas * *mkl       # [x86]
        - liblapack * *mkl       # [x86]
        - libblas * *openblas               # [not x86]
        - libcblas * *openblas             # [not x86]
        - liblapack * *openblas            # [not x86]
        - openblas             # [not x86]
        - openfst  # [not win]

about:
  home: http://kaldi-asr.org/
  license: Apache-2.0
  license_file: COPYING
  summary: 'Kaldi is a toolkit for speech recognition written in C++.'
  description: |
    Kaldi is intended for use by speech recognition researchers. It is a framework rather than a library.
  doc_url: http://kaldi-asr.org/doc
  dev_url: http://kaldi-asr.org/forums.html

extra:
  recipe-maintainers:
    - mmcauliffe
    - mcernak
