{% set version = "5.5.992" %}
{% set commit = "a92babfe74532bc2612d7f342d8f668e592413f9" %}

package:
  name: kaldi
  version: {{ version }}

source:
  fn: {{ version }}-{{ commit }}.tar.gz
  url: https://github.com/kaldi-asr/kaldi/archive/a92babfe74532bc2612d7f342d8f668e592413f9.tar.gz
  sha256: 66f3731e0c23efed870e8956be876436ffe44ea823814c895af779531904715b
  patches:
    - cmake.patch

build:
  number: 4

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}  # [not win]
    #- {{ compiler('cuda') }}  # [cuda_compiler_version != "None"]
    - cmake
    - ninja
    - m2-patch  # [win]
    - libtool  # [not win]
    - automake  # [not win]
  host:
    - pthreads-win32        # [win]
    - mkl-devel             # [x86 and build_platform == target_platform]
    - mkl        # [x86]
    - libblas * *mkl       # [x86 and build_platform == target_platform]
    - libcblas * *mkl       # [x86 and build_platform == target_platform]
    - liblapack * *mkl       # [x86 and build_platform == target_platform]
    - libblas               # [not x86 or build_platform != target_platform]
    - libcblas              # [not x86 or build_platform != target_platform]
    - liblapack             # [not x86 or build_platform != target_platform]
    - openblas              # [not x86 or build_platform != target_platform]
    - blas-devel            # [not x86 or build_platform != target_platform]
    - zlib
    - icu
  run:
    - mkl         # [x86 and build_platform == target_platform]
    - libblas * *mkl       # [x86 and build_platform == target_platform]
    - libcblas * *mkl       # [x86 and build_platform == target_platform]
    - liblapack * *mkl       # [x86 and build_platform == target_platform]
    - libblas               # [not x86 or build_platform != target_platform]
    - libcblas              # [not x86 or build_platform != target_platform]
    - liblapack             # [not x86 or build_platform != target_platform]

test:
  requires:
    - openfst  # [not win]

about:
  home: http://kaldi-asr.org/
  license: Apache-2.0
  license_file: COPYING
  summary: 'Kaldi is a toolkit for speech recognition written in C++.'
  description: |
    Kaldi is intended for use by speech recognition researchers. It is a framework rather than a library.
  doc_url: http://kaldi-asr.org/doc
  dev_url: http://kaldi-asr.org/forums.html

extra:
  recipe-maintainers:
    - mmcauliffe
    - mcernak
