{% set version = "r7271.1a4dbf6" %}
{% set commit = "1a4dbf6be118e4967cf4efd510811ef72cdfee3d" %}

package:
  name: kaldi
  version: {{ version }}

source:
  fn: {{ version }}-{{ commit }}.tar.gz
  url: https://github.com/kaldi-asr/kaldi/archive/{{ commit }}.tar.gz
  sha256: 70dd0dd1ca0b66a5c8726ea40861da001a721563c2984b55ea5c2c236e89e5c8
  patches:
    # Kaldi builds in place, so the patch makes just compilation of
    # the libraries in ${PREFIX}/lib; in addition, it contains sources
    # of two additional binaries for UBM MAP adaptation and scoring.
    - conda-kaldi.patch

build:
  number: 3
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - openfst
    - openblas
    - speex
  run:
    - openfst
    - openblas
    - speex

about:
  home: http://kaldi-asr.org/
  license: Apache-2.0
  license_file: COPYING
  summary: 'Kaldi is a toolkit for speech recognition written in C++.'
  description: |
    Kaldi is intended for use by speech recognition researchers. It is a framework rather than a library.
  doc_url: http://kaldi-asr.org/doc
  dev_url: http://kaldi-asr.org/forums.html

extra:
  recipe-maintainers:
    - mcernak
