{% set version = "5.5.1112" %}
# minor/major is https://github.com/kaldi-asr/kaldi/blob/master/src/.version;
# patch version is the number of commits since then, see
# https://github.com/kaldi-asr/kaldi/blob/master/cmake/VersionHelper.cmake
{% set commit = "8c451e28582f5d91f84ea3d64bb76c794c3b1683" %}
{% set kaldi_proc_type = "cuda" if cuda_compiler_version != "None" else "cpu" %}

{% set kaldi_libraries = [
    "base", "matrix", "cudamatrix", "util", "feat", "tree", "gmm", "transform",
    "fstext", "hmm", "lm", "decoder", "lat", "nnet", "nnet2", "nnet3",
    "rnnlm", "chain", "ivector", "online", "online2", "kws"
] + (cuda_compiler_version is defined and cuda_compiler_version != "None") * [
    "cudafeat", "cudadecoder"
]%}
# This list should be substantially longer, but upstream just globs
# all *.h files. These are just stand-ins (one header per folder),
# but relevant headers can be added as needed/desired.
{% set kaldi_headers = [
    "base/io-funcs.h", "matrix/cblas-wrappers.h", "cudamatrix/cu-array.h",
    "util/basic-filebuf.h", "feat/feature-common.h", "tree/build-tree.h",
    "gmm/am-diag-gmm.h", "transform/cmvn.h",
    "fstext/context-fst.h", "hmm/hmm-utils.h", "lm/arpa-file-parser.h",
    "decoder/grammar-fst.h", "lat/arctic-weight.h", "nnet/nnet-activation.h",
    "nnet2/am-nnet.h", "nnet3/attention.h", "rnnlm/sampler.h",
    "chain/chain-datastruct.h", "ivector/plda.h", "online/online-decodable.h",
    "online2/online-endpoint.h", "kws/kaldi-kws.h", "itf/options-itf.h"
] + (cuda_compiler_version != "None") * [
    "cudafeat/lane-desc.h", "cudadecoder/cuda-fst.h"
] %}

package:
  name: kaldi-split
  version: {{ version }}

source:
  url: https://github.com/kaldi-asr/kaldi/archive/{{ commit }}.tar.gz
  sha256: ca169b55f21c7a8420b023ad94b17bfcc9bb0c025bacf2ab3330171ab33d7e08
  patches:
    # Patches based on https://github.com/kaldi-asr/kaldi/pull/4829
    - patches/0001-Support-openfst-1.7.6.patch
    - patches/0002-Support-openfst-1.8.0.patch
    - patches/0003-Support-openfst-1.8.1.patch
    - patches/0004-Support-openfst-1.8.2.patch
    - patches/0005-Shared-libraries-on-windows.patch
    - patches/0006-Cuda-12-support.patch  # [(cuda_compiler_version or "").startswith("12")]

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}

outputs:
  - name: kaldi
    build:
      string: cuda{{ cuda_compiler_version | replace('.', '') }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
      string: cpu_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}                                                # [cuda_compiler_version == "None"]
      run_exports:
        - {{ pin_subpackage('kaldi', max_pin='x.x.x') }}
    script: build_kaldi.sh   # [not win]
    script: build_kaldi.bat  # [win]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ compiler('fortran') }}  # [not win]
        - {{ compiler('cuda') }}     # [cuda_compiler_version != "None"]
        - cmake
        - ninja
        - m2-patch  # [win]
        - libtool   # [not win]
        - automake  # [not win]
      host:
        - cuda-version {{ cuda_compiler_version }}  # [cuda_compiler_version != "None"]
        - cuda-profiler-api                         # [(cuda_compiler_version or "").startswith("12")]
        - cuda-nvtx-dev                             # [(cuda_compiler_version or "").startswith("12")]
        - cuda-cudart-dev                           # [(cuda_compiler_version or "").startswith("12")]
        - cuda-driver-dev                           # [(cuda_compiler_version or "").startswith("12")]
        - cuda-nvrtc-dev                            # [(cuda_compiler_version or "").startswith("12")]
        - libcublas-dev                             # [(cuda_compiler_version or "").startswith("12")]
        - libcurand-dev                             # [(cuda_compiler_version or "").startswith("12")]
        - libcufft-dev                              # [(cuda_compiler_version or "").startswith("12")]
        - libcusolver-dev                           # [(cuda_compiler_version or "").startswith("12")]
        - libcusparse-dev                           # [(cuda_compiler_version or "").startswith("12")]
        - icu
        - libblas
        - libcblas
        - liblapack
        - liblapacke
        - magma                                     # [cuda_compiler_version != "None"]
        - pthreads-win32                            # [win]
        - zlib
        - openfst ==1.8.3
        - dlfcn-win32                               # [win]
      run:
        - libblas
        - libcblas
        - liblapack
        - liblapacke
        - magma                                     # [cuda_compiler_version != "None"]
        - openfst ==1.8.3
        - ucrt                                      # [win]
    test:
      # will also run run_test.py (checking the binaries)
      commands:
        # libraries:
        {% for each_lib in kaldi_libraries %}
            # shared
            - test -f $PREFIX/lib/libkaldi-{{ each_lib }}.so               # [linux]
            - test -f $PREFIX/lib/libkaldi-{{ each_lib }}.dylib            # [osx]
            - if not exist %LIBRARY_BIN%\kaldi-{{ each_lib }}.dll exit 1   # [win]
            - if not exist %LIBRARY_LIB%\kaldi-{{ each_lib }}.lib exit 1   # [win]

            # absence of static libraries
            - test ! -f $PREFIX/lib/libkaldi-{{ each_lib }}.a              # [not win]
        {% endfor %}

        # headers:
        {% for each_header in kaldi_headers %}
            - test -f $PREFIX/include/kaldi/{{ each_header }} || (echo "{{ each_header }} not found" && exit 1)  # [unix]
            - if not exist %LIBRARY_INC%\kaldi\{{ "\\".join(each_header.split("/")) }} exit 1                    # [win]
        {% endfor %}

about:
  home: http://kaldi-asr.org/
  license: Apache-2.0
  license_file: COPYING
  summary: 'Kaldi is a toolkit for speech recognition written in C++.'
  description: |
    Kaldi is intended for use by speech recognition researchers. It is a framework rather than a library.
  doc_url: http://kaldi-asr.org/doc
  dev_url: https://github.com/kaldi-asr/kaldi

extra:
  recipe-maintainers:
    - mmcauliffe
    - mcernak
    - h-vetinari
  feedstock-name: kaldi
