build_platform:
  osx_arm64: osx_64
azure:
  settings_win:
    pool:
      vmImage: windows-2019
provider: { win: azure }
conda_forge_output_validation: true
test_on_native_only: true
os_version:
  linux_64: cos7
