azure:
  settings_win:
    pool:
      vmImage: windows-2019
build_platform:
  osx_arm64: osx_64
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
os_version:
  linux_64: cos7
provider:
  win: azure
test_on_native_only: true
